### ISSUE TITLE
Mismatched OTP

### ISSUE THREAD

**Issue by hrump** [django-otp/yubiotp#1]
When I generate an OTP using these libraries I get a different result than when I use https://github.com/Yubico/yubico-c. It seems to be a difference in the encryption step. I compare the OTP data before encryption and it's the same on both code bases, but after encryption it's different. Further, if I use an encryption key of all Zeros then I get the same output. 

Any idea how to reconcile the difference?

**Comment by psagers** [comment]
It's been years since I looked at this, especially now that U2F is everywhere. However, glancing at the code, it appears that the Yubico OTP algorithm incorporates a random element in the encrypted token. Perhaps that's the discrepancy.

Are you tracking down a real-world problem or just exploring?

**Comment by hrump** [comment]
Hey, thanks for the response. Unfortunately the email notification ended up in spam so I didn't see it until now. I discovered that the Yubico application must be fed lowercase strings only. Any upper case characters evaluate to zero which is why my "zeroes" test was passing.
